apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: iesniegumi.pilsetacilvekiem.lv
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_PASSWORD
              name: api-env
        - name: BASIC_AUTH_REALM
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_REALM
              name: api-env
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_USERNAME
              name: api-env
        image: iesniegumipilsetacilvekiemlv.azurecr.io/iesniegumugenerators
        name: api
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: app
      restartPolicy: Always
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: iesniegumi.pilsetacilvekiem.lv
status: {}
