apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - args:
        - /app/run.sh
        env:
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_PASSWORD
              name: api-env
        - name: BASIC_AUTH_REALM
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_REALM
              name: api-env
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              key: BASIC_AUTH_USERNAME
              name: api-env
        image: elixir:1.9.1-alpine
        name: api
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
