apiVersion: apps/v1
kind: Deployment
metadata:
  name: iesniegumi.pilsetacilvekiem.lv
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: iesniegumipilsetacilvekiemlv.azurecr.io/iesniegumugenerators
          name: api
          ports:
            - containerPort: 4000
  replicas: 1
