apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: iesniegumugenerators 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iesniegumugenerators 
    spec:
      containers:
        - name: iesniegumugenerators 
          image: iesniegumipilsetacilvekiemlv.azurecr.io/iesniegumugenerators
          ports:
          - containerPort: 80