apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iesniegumi.pilsetacilvekiem.lv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 32Gi
